name: SAST

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  semgrep:
    name: Semgrep SAST Scan
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        run: semgrep scan --config=p/javascript --config=p/nodejs --config=p/owasp-top-ten --error .
